[package]
edition = "2021"
name = "day13"
version = "0.1.0"

[[example]]
name = "part1"

[[example]]
name = "part2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
